google_ads:
  developer_token: "SUA_DEVELOPER_TOKEN"
  client_id: "SEU_CLIENT_ID"
  client_secret: "SEU_CLIENT_SECRET"
  refresh_token: "SEU_REFRESH_TOKEN"
  customer_id: "SUA_CUSTOMER_ID"
report:
  start_date: "2024-06-01"
  end_date: "2024-06-15"
  metrics:
    - campaign.id
    - campaign.name
    - metrics.impressions
    - metrics.clicks
    - metrics.cost_micros
email:
  enabled: true
  smtp_server: smtp.gmail.com
  smtp_port: 587
  username: seu_email@gmail.com
  password: sua_senha_de_app
  from: seu_email@gmail.com
  to: destinatario@gmail.com
schedule_minutes: 1440 # 1 vez por dia
